title: Jared DiPietro
email: jared135@hotmail.ca
baseurl: "https://imposerr.github.io"
url: "/Portfolio_Site"


collections:
  design:
    output: true
    permalink: /:collection/:path/

sass:
  style: compact

permalink: /:categories/:title/